name = "PCHIPInterpolation"
uuid = "afe20452-48d1-4729-9a8b-50fb251f06cd"
authors = ["Gabriel S. Gerlero <ggerlero@cimec.unl.edu.ar>", "Pablo A. Kler"]
version = "0.1.3"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
ArgCheck = "2"
RecipesBase = "1"
julia = "1.5"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ForwardDiff", "Plots", "Test"]
